packages:
  # executable/launchable applications
  - 'apps/*'
  # all packages in subdirs of packages/ and components/
  - 'packages/*'
  
  # Game client (frontend) and server (backend) directories
  - 'client'
  - 'server'
